language: julia
os:
  - linux
julia:
  - 0.5
notifications:
  email:
    recipients:
      - sunbergzach@gmail.com
    on_failure: always
    on_success: change
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --check-bounds=yes -e 'Pkg.clone("https://github.com/sisl/POMDPs.jl"); Pkg.clone("https://github.com/sisl/POMDPModels.jl"); Pkg.clone("https://github.com/sisl/POMDPDistributions.jl"); Pkg.clone("https://github.com/sisl/POMDPToolbox.jl"); Pkg.clone("https://github.com/JuliaPOMDP/GenerativeModels.jl"); Pkg.add("NBInclude"); Pkg.clone(pwd()); Pkg.test("MCTS"; coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("MCTS")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  - julia -e 'Pkg.clone("https://github.com/JuliaDocs/Documenter.jl")'
  - julia -e 'cd(Pkg.dir("MCTS")); include(joinpath("docs", "make.jl"))'
